Section "InputClass"
    Identifier "Shift Layout virtual mouse button scrolling"
    MatchProduct "Shift Layout Mouse Proxy"
    MatchIsPointer "on"
    Driver "libinput"
    Option "ScrollMethod" "button"
    Option "ScrollButton" "8"
    Option "ScrollButtonLock" "false"
EndSection
